package com.seraphel.shooting.master.extend.enumerate;

public enum PropertyType {

    CURRENT_FRAME,
    X_AXIS_POSITION,
    Y_AXIS_POSITION,
    RADIUS,
    RADIUS_DEGREE,
    COUNT,
    CYCLE,
    ANGLE,
    RANGE,

    LAUNCHER_SPEED,
    LAUNCHER_SPEED_DIRECTION,
    LAUNCHER_ACCELERATION,
    LAUNCHER_ACCELERATION_DIRECTION,

    BULLET_LIFE,
    BULLET_TYPE,
    BULLET_SCALE_X,
    BULLET_SCALE_Y,
    BULLET_TOWARD,
    BULLET_COLOR_ALPHA,
    BULLET_COLOR_R,
    BULLET_COLOR_G,
    BULLET_COLOR_B,

    BULLET_SPEED,
    BULLET_SPEED_DIRECTION,
    BULLET_ACCELERATION,
    BULLET_ACCELERATION_DIRECTION,
    HORIZONTAL_RATIO,
    VERTICAL_RATIO,

    DISAPPEAR_OUT_SCREEN,
    DISAPPEAR_EFFECT,
    TAIL_EFFECT

}
